-- join 을 이용하는 문제. from 에서 해당 테이블을 지정해주지 않아도 join 을 이용해 묶어주면 select 로 가지고 올 수가 있다.
SELECT UB.TITLE, UR.BOARD_ID, UR.REPLY_ID, UR.WRITER_ID, UR.CONTENTS, DATE_FORMAT(UR.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE 
FROM USED_GOODS_REPLY AS UR
INNER JOIN USED_GOODS_BOARD AS UB ON UB.BOARD_ID = UR.BOARD_ID
WHERE UB.CREATED_DATE LIKE '2022-10%'
ORDER BY UR.CREATED_DATE, UB.TITLE
